name: TodoTray
options:
  bundleIdPrefix: com.todo-tray
  deploymentTarget:
    macOS: "14.0"
  generateEmptyDirectories: true
  groupSortPosition: top

settings:
  base:
    PRODUCT_NAME: TodoTray
    PRODUCT_BUNDLE_IDENTIFIER: com.todo-tray.app
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "14.0"
    CODE_SIGN_STYLE: Automatic
    ENABLE_HARDENED_RUNTIME: NO
    CODE_SIGN_IDENTITY: "-"
    INFOPLIST_FILE: TodoTray/Info.plist

targets:
  TodoTray:
    type: application
    platform: macOS
    sources:
      - path: TodoTray/Sources
        excludes:
          - "**/.DS_Store"
          - "todo_tray_core.swift"
      - path: TodoTray/Generated/todo_tray_core.swift
        optional: true
        type: file
    settings:
      base:
        INFOPLIST_FILE: TodoTray/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.todo-tray.app
        LD_RUNPATH_SEARCH_PATHS:
          - "$(inherited)"
          - "@executable_path/../Frameworks"
        LIBRARY_SEARCH_PATHS:
          - "$(inherited)"
          - "$(SRCROOT)/TodoTray/todo_tray_core.xcframework/macos-arm64"
        OTHER_LDFLAGS:
          - "-ltodo_tray_core"
          - "-framework"
          - "Cocoa"
          - "-framework"
          - "UserNotifications"
          - "-framework"
          - "SystemConfiguration"
          - "-framework"
          - "Security"
          - "-liconv"
        SWIFT_INCLUDE_PATHS:
          - "$(SRCROOT)/TodoTray/Generated"
        HEADER_SEARCH_PATHS:
          - "$(SRCROOT)/TodoTray/Generated"
    entitlements:
      path: TodoTray/TodoTray.entitlements
      properties:
        com.apple.security.app-sandbox: false
    preBuildScripts:
      - name: Build Rust Core
        script: |
          set -e
          cd "$SRCROOT/.."
          
          # Remove old xcframework to ensure fresh build
          rm -rf "$SRCROOT/TodoTray/todo_tray_core.xcframework"
          
          # Build Rust library
          cargo build -p todo-tray-core --release --target aarch64-apple-darwin
          
          # Generate Swift bindings
          mkdir -p "$SRCROOT/TodoTray/Generated"
          cargo run -p todo-tray-core --bin uniffi-bindgen generate \
            --library target/aarch64-apple-darwin/release/libtodo_tray_core.a \
            --language swift \
            --out-dir "$SRCROOT/TodoTray/Generated"
          
          # Rename modulemap
          if [ -f "$SRCROOT/TodoTray/Generated/todo_tray_coreFFI.modulemap" ]; then
            mv "$SRCROOT/TodoTray/Generated/todo_tray_coreFFI.modulemap" \
               "$SRCROOT/TodoTray/Generated/module.modulemap"
          fi
          
          # Create xcframework
          xcodebuild -create-xcframework \
            -library target/aarch64-apple-darwin/release/libtodo_tray_core.a \
            -headers "$SRCROOT/TodoTray/Generated" \
            -output "$SRCROOT/TodoTray/todo_tray_core.xcframework"
        basedOnDependencyAnalysis: false
        showEnvVars: false
        outputFiles:
          - $(SRCROOT)/TodoTray/Generated/todo_tray_core.swift
          - $(SRCROOT)/TodoTray/Generated/module.modulemap
          - $(SRCROOT)/TodoTray/todo_tray_core.xcframework
